### ISSUE TITLE
default target branch no longer aligned with github standards

### ISSUE THREAD

**Issue by francispeixoto** [cpina/github-action-push-to-another-repository#15]
github has changed its branch structure policy to favor 'main' as the default branch name.

In the action, unless 'target-branch' is forced to 'main', the default is still master.

**Comment by cpina** [comment]
Thanks @francispeixoto for the issue . I had thought of this and the change would be backwards incompatible: if I changed the default branch and users updated to a new version: the behaviour would change unless they had specified the branch "master". That's why I haven't changed it yet.

I think that there are two options:
 * Make the default target branch argument mandatory in a new version. It will fail for users that don't specify it, they will need to specify it. Document this as clear as possible
 * Change the default branch to "main", and if it doesn't exist show a clear error message saying that it doesn't exist and that this is a change for X version

Any opinions from anyone?

Thanks!

**Comment by francispeixoto** [comment]
i would probably go with the first option. as a developer, it's probably a better practice to explicitly understand and control your entire deploy flow rather than rely on the action maintainer keeping up with changing standards for critical parts of it like the source of the content ;)

**Comment by cpina** [comment]
Thanks - I will wait one or two weeks to see if other people suggest anything else and probably make the change for the next release. That was a bit of oversight when I did it optional.

**Comment by arnavs** [comment]
I think one option is to check if `main` and `master` exist, and then choose based on that. i.e...

1. If none exist, throw an error. 
2. If one exists, use it. 
3. If both exists, use a default. (Could be either one, depending on your preference.)

**Comment by cpina** [comment]
@arnavs : I like this idea, I really need to look into this soon (the master-main thing). Thanks for the reminder!

**Comment by robertlugg** [comment]
I would like to suggest something that might be quicker for you and may be sufficient.  In your example where you are generating those panda docs, you give most of the arguments, but not target-branch.  My suggestion is to add into the example

    target-branch: master

Just having it explicit would let us know that we need to change it.

**Comment by cpina** [comment]
> I would like to suggest something that might be quicker for you and may be sufficient. In your example where you are generating those panda docs, you give most of the arguments, but not target-branch. My suggestion is to add into the example
> 
> ```
> target-branch: master
> ```
> 
> Just having it explicit would let us know that we need to change it.

Yes, I might end up doing this to keep it simple and explicit... (less checks). Still in my to do list :-) thanks!

**Comment by cpina** [comment]
I've updated the example to add the TARGET_BRANCH so it's more visible.

I might make more improvements here in the future (e.g. the default to be main and if it fails to master).

Thanks for all your comments.

**Comment by cpina** [comment]
`target-branch` is `main` in `main` (but not in `v1.3`). I will release `v1.4` next week probably.
