### ISSUE TITLE
Why are all the files getting deleted. 

### ISSUE THREAD

**Issue by abvijaykumar** [cpina/github-action-push-to-another-repository#61]
Hi I just noticed and read in the readme that the target folder is cleared. Why can't I just push the changes..rather than clearing the target

**Comment by cpina** [comment]
Hi @abvijaykumar - thank you for your comment.

The action was designed for clearing the target folder in order to have a "mirror". This doesn't suite everyone so there is a ticket to allow to keep all/certain files (https://github.com/cpina/github-action-push-to-another-repository/issues/58)

Before adding more flags I really want to add tests. I'm trying to find time for this at the moment! :-) : https://github.com/cpina/github-action-push-to-another-repository/issues/59

At the moment you could, in your GitHub action, download the files before pushing the directory (I haven't tested and I don't have a copy-paste code for this right now).

I'll close your requested as it's covered by https://github.com/cpina/github-action-push-to-another-repository/issues/58 . Thanks again for reaching out, it helps to know what's wanted or not :-)
