### ISSUE TITLE
Question: How are "missing" files handled?

### ISSUE THREAD

**Issue by jacquelinegarrahan** [cpina/github-action-push-to-another-repository#62]
Hi, 

For our workflow we generate a number of artifacts based on our main repository branch and are pushing those artifacts to a separate repo. How does this workflow handle files that might be removed? Will those still be available in the git history of the target repo or is the entire history overwritten?

Thanks

**Comment by cpina** [comment]
Hi @jacquelinegarrahan ,

History is preserved. The files that were there and not anymore can be seen in the latest git commit.

For example, I pushed a new file that got deleted by the GitHub action. The file was new_file.txt. The latest commit done by the action is:
https://github.com/cpina/push-to-another-repository-output/commit/a856a4a5d907ddb0904dd1234fc20771799cabc1

new_file.txt was pushed manually but it would have been the same if it was there because it was previously build.

I'll close this issue but feel free to re-open if you have any follow up question!

**Comment by jacquelinegarrahan** [comment]
Thanks for your help & great project
