### ISSUE TITLE
remote: Permission to <destination-repo-name>.git denied to github-actions[bot]

### ISSUE THREAD

**Issue by Yijia-Chen** [cpina/github-action-push-to-another-repository#71]
![image](https://user-images.githubusercontent.com/38818142/171958581-12fc2cc1-2d02-4b37-8152-aa8776708e12.png)
I tried to update from a private repo to a public repo. My account has write access to both. The `API_TOKEN_GITHUB` is added as instructed in the source repo secrets. However, `git commit` seems to have no access to the destination repo.

Environment: Macbook M1 Pro

**Comment by Yijia-Chen** [comment]
Curious whether I need to add a personal access token somewhere in order for the permission to work correctly.

**Comment by cpina** [comment]
@Yijia-Chen : yes, you need to. I've just pushed some changes in `main` branch and you can use the personal access token or ssh keys (ssh keys recommended!). Even more: if you forget to do so now the action would let you know that you forgot.

If you are still interested try again.

**Comment by Yijia-Chen** [comment]
I had the `API_TOKEN_GITHUB` field before and just added the `SSH_DEPLOY_KEY` as well. However, the error remains the same. Do I need to add either or both of these tokens in the destination repo as well, or just the source repo?

**Comment by cpina** [comment]
Hi @Yijia-Chen . If you define the `API_TOKEN_GITHUB` and `SSH_DEPLOY_KEY` it will try using only the `SSH_DEPLOY_KEY`. Better choose one and focus on this one.

The recommended one is the `SSH_DEPLOY_KEY` (even though it has more steps). Let's try this one first?

For the `SSH_DEPLOY_KEY` you need to add the public key in the destination repo. Have you done it?
Could you try first of all in your computer:
```
ssh -o IdentitiesOnly=yes -i .ssh/id_push-to-another-repository-output_ed25519 git@github.com
```
(the `.ssh/id_push-to-another-repository-output_ed25519` is the **private** key)

You should see something like:
```
Hi cpina! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.
```
If you see:
```
git@github.com: Permission denied (publickey).
```

There is one more thing to check, I'll write it later if needed... (or if I have time).

**Comment by cpina** [comment]
If the ssh test that I mentioned in the comment before succeeds the other thing to check:
```
ssh-keygen -lf .ssh/id_push-to-another-repository-output_ed25519
```

The output will be like:
```
256 SHA256:SOME_STRING_OF_CHARACTERS carles@pina.cat (ED25519)
```

This should match what you see in the deploy key of the destination repo. If it does not match the deploy key is not properly set (you used different public/private key, etc.)

Also, very important, when you see the deploy key on GitHub it should say:
```
Read/write
```

I will try to take screenshots of all of this and update the documentation.

**Comment by cpina** [comment]
Separate comment with something to check easy:

- If you use `SSH_DEPLOY_KEY` it ignores the token
- Please check in the destination repo that the key was added and has "Read/Write" (in the Deploy Ssh keys section on GitHub of the destination repo)
- Make sure that where you invoke the action you have something like: https://github.com/cpina/push-to-another-repository-deploy-keys-example/blob/main/.github/workflows/ci.yml#L24

And I will update the docs with screenshots and trouble shooting with what we are doing here :-) (not necessarily today)

**Comment by Yijia-Chen** [comment]
@cpina Thanks for your detailed response! Let me give this a try tomorrow and get back with my results here.

**Comment by Yijia-Chen** [comment]
Okay, @cpina for the step where you check by running this command
`ssh-keygen -lf .ssh/id_push-to-another-repository-output_ed25519`
My computer doesn't have this file under `~/.ssh/`, only `id_ed25519.pub` and `id_ed25519`. Would this be the problem?

**Comment by Yijia-Chen** [comment]
Both checks now pass but the issue persists. Do I need to push the Git Actions commits using the account given permission by the script? Perhaps that could be the issue. For clarification, I'm using a personal account for commits and a different "bot" account to perform this auto-push task.

**Comment by Yijia-Chen** [comment]
Should the `.ssh` directory be in the source directory? At the moment I'm using the system directory `~/.ssh`.

**Comment by cpina** [comment]
Hi @Yijia-Chen - I had missed something in your initial screenshot.

If it says "unable to access **https://.....**" (with HTTP) it really means that `SSH_DEPLOY_KEY` variable is not set (if you are using `main` branch... not the latest tagged one[1]). It also means that the `API_TOKEN_GITHUB` is not correct in the sense that maybe your user does not have permissions on the destination repo, copy-paste error pasting the token or wrong repo.

Is your source repo public? Can you send the URL here or by email? This way I can double check which branch you are using, the destination repo, etc.

If it is not public: confirm the error message (a screenshot like you did is good!) and double check the `API_TOKEN_GITHUB` if this is the way to go (so, follow the instructions to set it again since it cannot be read, double-check the destination repo name, etc.) and let me know how it goes.

You said:
> For clarification, I'm using a personal account for commits and a different "bot" account to perform this auto-push task.

I'm a bit confused with the setting but if this is public I can have a quick look with the setting and see if I see anything obviously wrong.

BTW, The `.ssh` directory does not need to exist in the source directory.

[1]:
In your `.github/workflows/ci.yml` you would have:
```
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
```
See the `@main` if it is the main branch.

**Comment by Yijia-Chen** [comment]
<img width="874" alt="image" src="https://user-images.githubusercontent.com/38818142/176571962-dd05a8b7-8fc1-4c4b-b775-f79d877f2839.png">

Ignore what I said earlier about the bot — now I'm using my own account for the `API_TOKEN_GITHUB`. The error persists, however, and I double checked that all fields are correct. The source directory is private and the destination is public, linked [here](https://github.com/curio-eth/engine-public).

One suspicion I have is that, because the agent doing the push is `github-action[bot]`, not my username, would I need to change some permission on the destination repo, for example allowing GitHub Action to push or adding an access token for GitHub Action?

**Comment by cpina** [comment]
@Yijia-Chen : apologies for being slow to answer. I will be monitoring this ticket for your feedback better! Also, thanks for your patience and sticking here :-)

I could reproduce the problem (exact error message) if I don't tick the "Repo" option on creating a new token. Are you sure that you ticked it?

![image](https://user-images.githubusercontent.com/489071/179087466-77d06b87-97c0-47fc-989d-0ff4cadd1e09.png)

Also: could it be that the token is expired? I've noticed that by default the tokens expire in 30 days.

Are you sure that you created the token with the correct user that you have permissions on the destination repository?

You can test the token. In the original repo you can do, in  your machine:

Are you using Bash / similar? You could do in your machine:
Replace each "$VARIABLE" with the right contents:

```
GIT_CMD_REPOSITORY="https://$DESTINATION_REPOSITORY_USERNAME:$API_TOKEN_GITHUB@$GITHUB_SERVER/$DESTINATION_REPOSITORY_USERNAME/$DESTINATION_REPOSITORY_NAME.git"
```
This should work (because your destination repo is public):
```
git clone --single-branch --branch "$TARGET_BRANCH" "https://$DESTINATION_REPOSITORY_USERNAME:$API_TOKEN_GITHUB@$GITHUB_SERVER/$DESTINATION_REPOSITORY_USERNAME/$DESTINATION_REPOSITORY_NAME.git" "just_the_name_of_a_directory"
```

This must work with the correct token:
```
cd just_the_name_of_a_directory
git push https://$DESTINATION_REPOSITORY_USERNAME:$API_TOKEN_GITHUB@$GITHUB_SERVER/$DESTINATION_REPOSITORY_USERNAME/$DESTINATION_REPOSITORY_NAME.git
```

This is to test the token without the github action. I still think that the token is either invalid, expired or something and I would try again from the github action before doing it manually. Just regenerate it, check that you use the GitHub account with permissions in the destination repo, that you tick "Repo" in the permissions, that the token is well setup in the origin repository. It's very easy to make a mistake :-) and have an old token there. Check the instructions step by step (even I want to improve the instructions with screenshots to help more!).

Please let me know how it goes. I will check answers tomorrow morning for sure and follow up :-)

**Comment by Yijia-Chen** [comment]
For `destination-github-username` and `destination-repository-username`, which one should be myself and which should be my organization which owns the repo?

**Comment by Yijia-Chen** [comment]
Ok I have another suspicion. I'm using my personal account, which is an owner and admin of my organization account, to do the push (because from my knowledge you cannot generate a "personal" access token for an org account). Would that be the problem?

**Comment by cpina** [comment]
> For `destination-github-username` and `destination-repository-username`, which one should be myself and which should be my organization which owns the repo?

I cannot remember the instructions but checking the action code:

- `destination-github-username`: your username (the personal username that you created the token with)
- `destination-repository-username`: the organisation name of the destination repository

I will revisit the documentation if this is not clear.

**Comment by Yijia-Chen** [comment]
The `repo` option is indeed checked. I also tried locally and the `git clone` and `git push` using the token both work. When the hook works, does the commit says it's from github-actions[bot] or from your username?

**Comment by Yijia-Chen** [comment]
Ok seems like I got a different error now! See screenshot

<img width="971" alt="image" src="https://user-images.githubusercontent.com/38818142/179291080-275dda6c-61ad-48e1-bc28-8708f532b990.png">
<img width="971" alt="image" src="https://user-images.githubusercontent.com/38818142/179291080-275dda6c-61ad-48e1-bc28-8708f532b990.png">

I changed `source-directory` from `.` (everything) to a specific folder name. Seems like now the commit is prepared, just the last step fails to have the right password or something. Any idea 1) what I can do to fix that, and 2) how I can port the entire repo as opposed to 1 folder?

**Comment by cpina** [comment]
For example, in my **global** `.gitconfig` I had (don't do this):
```
[url "git@github.com:"]
        insteadOf = https://github.com/
```
Which reverted my `https://github.com/` clone to use `git@github.com`. I could clone with the **wrong** token because it was reverting to git@github.com using my usual ssh setup :-)

That's why I'm asking to double check that when you use https it fails with the wrong token locally. To make sure that when you use the token it's really used.

**Comment by Yijia-Chen** [comment]
It indeed is using the token. If I modify any one character of it, it says `Invalid username or password`.

Just to make sure, I add the personal access token in the destination repo like the following by just pasting in the token value: 
![image](https://user-images.githubusercontent.com/38818142/179314419-1cd6d511-ce33-441a-982a-82d2135f9582.png)

This is correct?

**Comment by Yijia-Chen** [comment]
Ok it just worked! My mistake was that I was updating the token in the destination repo; instead it should be done in the source repo.

**Comment by Yijia-Chen** [comment]
Is there a way I can specify which branch on the source repo to track? For example, my default branch might be `develop`, but I want to track the `release` branch.

**Comment by cpina** [comment]
> Ok it just worked! My mistake was that I was updating the token in the destination repo; instead it should be done in the source repo.

:fireworks: I'm happy! :smile:

**Comment by cpina** [comment]
> Is there a way I can specify which branch on the source repo to track? For example, my default branch might be `develop`, but I want to track the `release` branch.

You can decide on which branches the job is used. Use GitHub syntax. For example, if you only want it for the main branch:
https://github.com/cpina/push-to-another-repository-example/blob/main/.github/workflows/ci.yml#L7

**Comment by cpina** [comment]
> I changed `source-directory` from `.` (everything) to a specific folder name. Seems like now the commit is prepared, just the last step fails to have the right password or something. Any idea 1) what I can do to fix that, and 2) how I can port the entire repo as opposed to 1 folder?

I've quickly tested to use as `.` (to do everything) as `source-directory`. It has the tricky thing that `.github/workflow/` is copied to the destination repository so it will trigger a build in the destination repository which might be confusing.

You could disable Actions in the **destination** repository. Click on `Settings` on the destination repository, then on the left hand side pane "Actions" then "General" and you can select "Disable Actions". So the actions will not run in the destination repo.

If you need actions on the destination repo you can use a way to filter actions based on the branch name or a variable as explained in https://docs.github.com/en/actions/using-workflows/triggering-a-workflow . Let me know if you need more specific guidance. But disabling the Actions in the destination repo might be the easier way if you can do it.

Note that I don't think that I ever tested using `.` as `source-directory`. If you have problems you can have a step before the action that moves files to a specific directory and copy this one (if you want to start excluding files). I should document how to do this as it's a work around of a possible feature.

**Comment by Yijia-Chen** [comment]
Yes, the last paragraph you mentioned would be very helpful. In addition, it would be great if there's a way to "test port" the repo without actually publishing it there, because I wish to keep my public repo's commit history clean. Please let me know if/once you add those. But generally, thanks a lot for your responses and helping me figure out solutions!

**Comment by cpina** [comment]
> Yes, the last paragraph you mentioned would be very helpful

I will add an example on how to add / exclude files and add a comment here.

**Comment by cpina** [comment]
> it would be great if there's a way to "test port" the repo without actually publishing it there, because I wish to keep my public repo's commit history clean

If testing things you made some mistakes you can fix them using git rebase or git push --force. It might help you but please read the consequences of rewriting git's history! But technically it works.
